[package]
name = "wymrs"
version = "0.1.0"
authors = ["Jordan Danford <jordandanford@gmail.com>"]
edition = "2021"

[dependencies]
lazy_static = "1.4"
num = "0.4"
palette = { version = "0.7", features = [] }
rand = "0.8"
rand_distr = "0.4"
sdl2 = "0.35"
